services:
  app:
    build: .
    depends_on:
      - redis
      - db
      - migrate
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/splits-api"
      REDIS_URL: "redis://redis:6379"
    env_file:
      - .env
    ports:
      - "3000:3000" # Expose your app on port 3000 or the port it uses
    command: ["node", "src/app.js"]

  migrate:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/splits-api"
    env_file:
      - .env
    command: ["npm", "run", "db:migrate"]

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379" # Redis default port

  db:
    image: "postgres:16-alpine"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "splits-api"
    ports:
      - "5432:5432" # PostgreSQL default port
